language: node_js
node_js:
  - "lts/*" # Latest LTS version
  - "16"
  - "12"

before_install: npm i -g npm@8.5.5

script:
   - npm run standards
   - npm test
   - commitlint-travis
   - rm -rf tmp-test # Clean up test dir
